version: '3.8'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
            - "24678:24678" # vite hmr
        restart: unless-stopped
        volumes:
            - .:/app
            - /app/node_modules